Kaspresso Shatravin (WS-5)
subbotin-d/RA pull request #13
Opened 2021-06-21 18:02 UTC by VladRaven5

2021-06-24 05:09 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/TodoListScreen.kt
> +        get() = KTextView {
Зачем здесь геттер?

2021-06-24 05:09 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/TodoListScreen.kt
> +            withText("Completed")
Я не рекомендую указывать здесь текст. Текстовки стоит проверять явно в тесте
```
filterMenuCompletedButton {
    hasText("Completed")
}
```

Во-первых: для идентификации контрола достаточно ID. 
Во-вторых: текст - это часть теста, поэтому лучше проверять его там

2021-06-24 05:09 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/SideDrawerScreen.kt
> +    fun showTaskListScreen() {
Есть много мнений на счет вот таких методов, которые делятся "можно"/"нельзя".

В целом, такое допускается, но работать надо с этим **аккуратно**, потому что можно потерять всю мощность инструмента и скатиться к скринам в espresso

2021-06-24 05:09 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        val newItemTitle = "My first kaspresso note title"
Для лучшей читаемости я бы рекомендовал текст вставить в то место, где осуществляется проверка.
Особой пользы от этих переменных нет

2021-06-24 05:09 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +                titleLabel.containsText(newItemTitle)
```
titleLabel {
    isDisplayed()
    hasText("My first kaspresso note title")
}
```

2021-06-24 05:09 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +            todoList.childAt<TodoListScreen.TodoListItem>(countBefore) {
`(countBefore)` - вот такой нейминг может легко ввести в ступор. Причем здесь countBefore, когда это позиция?

PS. Я понимаю что в данном случае они совпадают

2021-06-24 05:09 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +    private fun createTodo(title: String, description: String) {
Зачем эта функция? Она усложняет чтение теста, а не упрощает. 

А вдруг у тебя будет несколько разных путей создания туду, ты все будешь в функции оборачивать?

Рекомендую все это в явном виде прописывать в тесте, либо создать сценарий (при этом учесть, что сценарий должен быть максимально универсальный)
Пример: https://gist.githubusercontent.com/matzuk/73a96192bf7268f90d889447aab52134/raw/76c8018951f8bfdb980ca68815975ee4edf56bb1/scenario.kt

2021-06-24 05:09 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        val countBefore = TodoListScreen.todoList.getSize()
Перед выполнением теста стоит озаботиться настройкой окружения, чтобы сделать предсказуемый тест.

К примеру, в этом тесте мы заранее знаем что countBefore будет всегда равен 2 (из-за особенности приложения). Тогда зачем эти переменные тут?

2021-06-24 05:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        if(countBefore <= 0)
Слишком оверкильно получилось) Стоит помнить что тест - это сценарий. И в тесте должно быть ровно 0 логики

https://github.com/subbotin-d/RA/pull/13/files#r657629406

2021-06-24 05:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        var removingItemTitle : String = ""
Почему бы заранее не определить айтем, который хочется удалить?

2021-06-24 05:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        TodoListScreen.todoList.childAt<TodoListScreen.TodoListItem>(countBefore - 1) {
Лучше использовать синтаксис с "{"

2021-06-24 05:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +            removingItemTitle = titleLabel.getText()
Никакой логики в теста, никакой!)

2021-06-24 05:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +    fun checkCompletedTodoFilter() {
Очень тяжко читать этот тест. Нужно поработать над соблюдением код стайла. Например везде использовать "{". Общие блоки группировать 

```
todoList {
    hasSize(1)

    children<TodoListScreen.TodoListItem> {
                titleLabel.hasText(completedTodoTitle)
    }
}
```

2021-06-24 05:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +            completedCount = 1
Очень уж странно код выглядит, а почему сразу во время инициализации не присвоил 1?)

BTW, эти переменные не нужны. Ты заранее все данные знаешь

2021-06-24 05:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +            activeTasksLabel.containsText("${(100.0 * (countAll - completedCount) / countAll).truncate(1)}%")
Ты заранее знаешь цифры)

2021-06-24 05:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +    fun KTextView.getText() : String {
Это бы не понадобилось, если бы ты не создавал лишних сущностей и доп. логики в тестах

2021-06-24 05:21 UTC, subbotin-d requested changes
Резюме:

1. Хорошая работа, видно что хотел сделать все "стабильно"
2. Круто что ты написал самостоятельно кастомный экшен, хотя он тебе и не нужен был. Но в будущем это придется делать, так что "+" за это)
2. Сильно перемудрил с тестами. Тесты должны быть линейны, без какой-либо логики внутри (бывают исключения, но очень редко и не в твоем случае).
3. Стоит огромное внимание уделить кодстайлу. Чтобы тест было удобно читать нужно чтобы везде было однообразие. Я рекомендую использоваться лямбды("{") вместо обычных вызовов функций(через точку)

2021-06-24 05:21 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +    class GetTextAction : ViewAction {
https://github.com/subbotin-d/RA/pull/13/files#r657632468

2021-06-24 05:22 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/SideDrawerScreen.kt
> +    fun showTaskListScreen() {
Неймнг надо поменять, не show, а open

2021-06-24 05:31 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/TodoListScreen.kt
> +        get() = KTextView {
Насколько я помню, там проблема была в следующем. На момент старта приложения выпадающего списка еще нет на экране (в иерархии вьюх), а поле уже пытается проинициализироваться. В итоге тест падает так как у вьюхи нет матчей

2021-06-24 05:33 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/TodoListScreen.kt
> +            withText("Completed")
Там несколько элементов в выпадающего списке, у всех одинаковый id.title, но Completed из них только один
Потенциально, доступ к кнопке Completed мог понадобиться в разных местах, поэтому вынес его в screen object

2021-06-24 05:35 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/SideDrawerScreen.kt
> +    fun showTaskListScreen() {
Ну от этой логики никуда не деться, если я правильно понимаю. Она будет либо аккуратно инкапсулирована в screen object,  либо будет продублирована в каждом тесте, где нужна. Или есть ещё какие-то альтернативы?

2021-06-24 05:38 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        val newItemTitle = "My first kaspresso note title"
Согласен. Просто в перспективе бывает удобно проверить тест на каких-то других значениях. И в таких случаях проще поменять значение в одном месте, чем сразу в двух)

2021-06-24 05:49 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        val countBefore = TodoListScreen.todoList.getSize()
Это сейчас два) А потом что-то изменится, и половину тестов надо будет переписывать)
В принципе, если тестировать приложение без данных, и прям перед прогонами тестов заполнять определёнными данными - то да, такую логику можно будет исключить. А в текущем варианте исключать небезопасно)

2021-06-24 05:52 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        if(countBefore <= 0)
Я немного запутался, этот комментарий про реализацию removeLastTodo?
К сожалению, просто проверять каунт тут не сработает) при разработке очень легко, к примеру, запутаться в индексах, и вместо одного элемента удалить соседний. Тест по-прежнему будет проходить, но работать будет абсолютно неверно. Если замечание об этом)

2021-06-24 05:54 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +            removingItemTitle = titleLabel.getText()
Речь про removingItemTitle? Но ведь иначе мы не проверим, что удалилось именно то, что нужно)

2021-06-24 06:04 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +    private fun createTodo(title: String, description: String) {
О, это интересная штука, спасибо
Мне кажется, что наглядность тут нужна только в том тесте, где мы непосредственно тестируем создание. А в остальных, которым просто нужно каким-то образом создать новый туду для сценария, это не важно. Таких тестов, где процесс создания не важен, скорее всего будет больше одного. Поэтому я бы отдал предпочтение отдельному методу)

2021-06-24 06:08 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +            removingItemTitle = titleLabel.getText()
Тебе не нужно доставать текст, потому что ты изначально должен его знать. Я к тому, что перед началось теста ты должен подготовить "данные", о которых ты знаешь. В данном случае подготовка сделана за нас

2021-06-24 06:08 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +    fun KTextView.getText() : String {
Но ведь мы пишем тесты, чтобы быть уверенными в них )
В идеале, мне кажется, имеет смысл на этапе сетапа задавать исходные данные случайным образом. Так можно будет со временем выявить какие-то изначально непродуманные кейсы, которые случайным образом начнут воспроизводиться на сгенерированных данных. Но это довольно трудоёмко)

2021-06-24 06:11 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        if(countBefore <= 0)
Этот коммент про  if(countBefore <= 0)

Ничего не имею против того, что ты проверяешь что исчез айтем с указанным текстом. Просто я хочу донести то, что тебе не надо откуда-то доставить размер/текст итд. Ты их заранее знаешь, у тебя есть состояние "до" и "после". Состояние "до" тебе должно быть известно и состояние "после" тебе должно быть известно. Зачем какую-то логику наворачивать если все уже есть?)

В обычном проекте надо было бы писать обвязку, которая позволяет настроить состояние "до" - это верный путь. Писать логику в тестах - ложный путь

2021-06-24 06:14 UTC, VladRaven5 commented
Спасибо за замечания, постараюсь учесть)
По кодстайлу да, я сам пишу и плачу :D Очень непривычно после С# писать на котлине, особенно моменты с контекстами и замыкающими лямбдами )

2021-06-24 06:15 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        val countBefore = TodoListScreen.todoList.getSize()
Почему небезопасно?) Все безопасно)

Если ты понимаешь что надо делать настройку "до", то ок. Но будь аккуратен, не допускай логики в тестах вообще никогда, даже когда "небезопасно")

PS. Здесь можем условится, что все безопасно)

> А потом что-то изменится, и половину тестов надо будет переписывать
Если что-то меняется, то тест доже должен изменится, это нормальное стечение обстоятельств. Плохо, когда тест не меняется, это значит что он ничего не проверяет)

2021-06-24 06:17 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +    private fun createTodo(title: String, description: String) {
>Мне кажется, что наглядность тут нужна только в том тесте, где мы непосредственно тестируем создание. А в остальных, которым просто нужно каким-то образом создать новый туду для сценария, это не важно.

Все правильно говоришь. 

В том тесте, где цель проверить создание туду - пишем все внутри теста.
Во всех остальных, где цели другие - используем сценарии. 

Я здесь больше хотел тебе рассказать про "универсальные сценарии", подход мне понятен)

2021-06-24 06:19 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +        val newItemTitle = "My first kaspresso note title"
> И в таких случаях проще поменять значение в одном месте, чем сразу в двух

Спорный момент в контексте тестового сценария)
Тут у нас трейд-офф: читаемость-мнимая_переиспользуемость. Мое дело предостеречь)

2021-06-24 06:21 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/SideDrawerScreen.kt
> +    fun showTaskListScreen() {
Я бы писал все прям в тесте. 

Но как я уже сказал, писать так или сяк дело договоренностей команды. Главное быть аккуратным и не переборщить)

2021-06-24 06:37 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/TodoListScreen.kt
> +            withText("Completed")
Совсем забыл, что это "замечательное" menu. 
Тогда в целом все ок.

Кстати, можешь на досуге ради практики попробовать написать компонент бургерменю по подобию KRecyclerView (с childAt итд. Кроме withText можно еще искать по позиции предка(там будет сложный матчер) ).

2021-06-24 06:42 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/SideDrawerScreen.kt
> +object SideDrawerScreen : BaseScreen<SideDrawerScreen>() {
А что это за BaseScreen. Если это он
![image](https://user-images.githubusercontent.com/59696157/123214892-fb1b2880-d4f1-11eb-9374-2054a267c2c7.png), то это не правильно.

Должен быть Screen от Какао

2021-06-24 06:43 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/TodoListScreen.kt
> +        get() = KTextView {
Проблема может быть в https://github.com/subbotin-d/RA/pull/13/files#r657668019

2021-06-24 06:49 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/TodoListScreen.kt
> +        get() = KTextView {
Оу.
Спасибо, вечером проверю. Забыл что у какао свой базовый класс для so

2021-06-24 06:51 UTC, subbotin-d commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/test/kaspresso/TodoTests.kt
> +    fun KTextView.getText() : String {
> Но ведь мы пишем тесты, чтобы быть уверенными в них )

Именно поэтому "никакой логики в тестах", везде есть баги даже в тестах, а доп.логика это тот самый рассадник багов, которые могут сделать твой тест ложноположительным.

> В идеале, мне кажется, имеет смысл на этапе сетапа задавать исходные данные случайным образом

Имеет смысл, но только в ооооочень специфичных тестах. 
Если есть возможность сетапа, то надо устанавливать данные, которые каким-то образом программа обработает и выдаст результат, который и будет целью проверки.

Я не знаю во что должен превратиться тест, если мое приложение разными способами умеет обрабатывать разный type сущности, которую бэк присылает)
В этой ситуации я просто напишу N тестов, которые будут проверять определенный type. Это будет сильно проще в написании и сопровождении.

> Но это довольно трудоёмко

Это одна из причин, почему тесты делают как можно проще. Потому что потом их надо сопровождать. А если накрутить логики, то сопровождение превратится в ад и никто профита от тестов, кроме боли, не почувствует)

На тему рандома в тестах, не рекомендую, потому что в тестах все должно быть предсказуемо. Каждый тест имеет цель. А ежели это так, то мы знаем что ему надо на вход и что он должен дать на выход. Это суть тестирования)

2021-07-03 10:10 UTC, VladRaven5 commented on app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/screen/kaspresso/TodoListScreen.kt
> +        get() = KTextView {
Заменил базовый класс скрина на скрин от какао, помогло. Теперь работает без геттера, спасибо

2021-07-16 06:45 UTC, closed without merging