Workshop02 Shatravin Vlad
subbotin-d/RA pull request #8
Opened 2021-06-06 06:02 UTC by VladRaven5

2021-06-07 06:14 UTC, subbotin-d requested changes
Мощная работа

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    private val _dimensions : MutableList<Double> = MutableList<Double>(initialSize) { _ -> 0.0 }
Это тоже можно было оформить через backing property свойство, в котором был бы приватный set. Тогда бы это было более kotlin style.

Чтобы превратить все в kotlinStyle можно использовать концепцию backingField

```suggestion
    private var _dimensions : MutableList<Double> = MutableList<Double>(initialSize) { 0.0 }
    val dimensions: List<Double>
        get() = _dimensions
```

После этого надо удалить методы getValues, getValueOfDimensionInternal итд
Потому что доступ из вне будет к списку dimensions

vector.dimensions[0]

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +        var index = 0
```suggestion
constructor(vararg values : Double) : this(values.size) {
       _dimensions = values.toMutableList() // (на забыть _dimensions сделать var)
}
```

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    fun getValueOfDimension(dimensionIndex : Int) : Double {
Поехало форматирование=(

Если в intelijj idea / android studio выделить текст и нажать ctrl+alt+L, то IDE автоматически все выровняет как надо.

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    private fun getValueOfDimensionInternal(index : Int) : Double {
Зачем этот метод вообще?) если есть прямой доступ к _dimensions[index]

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    fun setValueOfDimension(dimensionIndex: Int, value : Double) {
Такого в задании не было)

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    fun dotProductWith(anotherVector: Vector) : Double {
![image](https://user-images.githubusercontent.com/59696157/120964315-5a0c3e00-c78d-11eb-9740-31a34a48aa15.png)

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +        for(index in 0 until size) {
Предлагаю использовать функции расширения для коллекций, чтобы перейти от императивного к декларативного стилю программирования:)
```suggestion
fun dotProductWith(anotherVector: Vector) : Double = _dimensions.mapIndexed { index, num -> 
        num * vector.dimensions[index] 
    }.fold(0.0) { acc: Double, num: Double ->
                acc + num
       }
           
```

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    private fun performJoinOperation(anotherVector : Vector, operation: (Double, Double) -> Double) : Vector {
Очень странное название метода) Оно говорит о том что мы "присоединяем", а по факту же мы просто складываем/вычитаем два вектора

В случае minus нейминг "join" вообще приходится не к месте. 
Стоит очень серьезно подходить к неймингу функций, потому что читать код потом становится болью

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    fun computeCosToVector(anotherVector: Vector) : Double {
a.cos(b) вот так же лучше?)

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    fun multiplyBy(multiplier : Double) {
Было бы очень круто, если бы привычные нам функции по типу "произведение на число"/"скалярное произведение"/"доступ к элементу вектора по индексу" были бы сделаны через функции операторы
![image](https://user-images.githubusercontent.com/59696157/120965749-7e691a00-c78f-11eb-9a01-0d439c82bf6a.png)
![image](https://user-images.githubusercontent.com/59696157/120965821-9476da80-c78f-11eb-96f7-600594d4ec0d.png)

Если следовать этому предложение, то коммент про backingField является не актуальным

ЗЫ: Плюс и минус уже сделаны)

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +open class Vector(initialSize : Int) : Comparable<Vector> {
Этот конструктор надо сделать вторичным. Так как связи между этим конструктором и другим вторичным вообще нет. Но при этом вторичный вынужден использовать первичный

2021-06-07 06:14 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    private fun getNormalizedIndex(dimensionIndex : Int) : Int = dimensionIndex-1; //dims 1-based, list 0-based
Для чего этот метод нужен?)

2021-06-07 06:14 UTC, subbotin-d commented on src/test/java/ws02/Vector3Test.kt
> +class Vector3Test {
Отельный жирный + за тесты!

2021-06-07 06:14 UTC, subbotin-d commented on src/test/java/ws02/VectorTest.kt
> +        assertTrue("compare correct", vector1 < vector2)
Всё круто! Но лучше помнить о том, что тесты (особенное юниты) надо дробить мелко, чтобы в  одном тесте была одна проверка.

2021-06-07 16:08 UTC, VladRaven5 commented on src/main/java/ws02/Vector.kt
> +    private val _dimensions : MutableList<Double> = MutableList<Double>(initialSize) { _ -> 0.0 }
Я как раз наоборот хотел скрыть внутреннюю реализацию хранения значений векторов) А через get/setValueOfDimension обеспечить контролируемый доступ извне)
Поэтому и появился метод getNormalizedIndex - чтобы преобразовать физический индекс измерения (обычно начинается с "1") в индекс списка.
А getInternal/setInternal возникли, когда решил изменить коллекцию с мапы на лист (когда увидел задание добавлять/удалять измерения) :)

2021-06-07 16:09 UTC, VladRaven5 commented on src/main/java/ws02/Vector.kt
> +    fun dotProductWith(anotherVector: Vector) : Double {
Я считал, что dot product. Оказывается оба варианта верны)
https://en.wikipedia.org/wiki/Dot_product

2021-06-07 16:12 UTC, VladRaven5 commented on src/main/java/ws02/Vector.kt
> +        for(index in 0 until size) {
А как в декларативном стиле можно реализовать предварительную проверку размерности векторов?
Сделать свой экстеншн метод, что-то вроде .throwIf( condition ), который или возвращает исходную коллекцию, или кидает эксепшн?

2021-06-07 16:21 UTC, VladRaven5 commented
@subbotin-d , спасибо за замечания!) На всякий случай уточню - от меня требуется доработка текущей реализации, или ДЗ принято?)

2021-06-08 04:40 UTC, subbotin-d commented
> @subbotin-d , спасибо за замечания!) На всякий случай уточню - от меня требуется доработка текущей реализации, или ДЗ принято?)

ДЗ принято, делать доработки - на твое усмотрение:)

2021-06-08 04:42 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +    private val _dimensions : MutableList<Double> = MutableList<Double>(initialSize) { _ -> 0.0 }
Да, я понял зачем это всё) В джава мире это ок) 
Ниже я накидал коммент с функциями операторами, они могли бы помочь в этом деле:)

2021-06-08 07:40 UTC, subbotin-d commented on src/main/java/ws02/Vector.kt
> +        for(index in 0 until size) {
Когда, я делал замечание, то не пропустил момент проверки.
Сделать можно вот так. Но читаемость имхо упадет

`
    operator fun minus(anotherVector: Vector): Vector = takeIf { this.components.size == anotherVector.components.size }
        ?.components
        ?.mapIndexed { index, num ->
            num - anotherVector[index]
        }
        ?.asVector() ?: throw IllegalArgumentException("A vector's size should be the same")
`

2021-06-15 03:22 UTC, closed without merging